# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sx_store', '0001_initial'),
        ('sx_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('isTrue', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_store.GoodsValue')),
            ],
            options={
                'verbose_name': '订单条目',
                'verbose_name_plural': '订单条目',
                'db_table': 'sx_order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=120, unique=True, verbose_name='订单号')),
                ('o_date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('o_date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('o_status', models.CharField(choices=[('NotPaid', '未支付'), ('Shipping', '运送中'), ('Shipped', '已收货'), ('Cancelled', '已取消'), ('Refunded', '已退款')], default='NotPaid', max_length=120)),
                ('o_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('o_address', models.CharField(max_length=150)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_user.UserModel')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'sx_order',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_store.GoodsValue')),
            ],
            options={
                'verbose_name': '销量',
                'verbose_name_plural': '销量',
                'db_table': 'sx_sales',
            },
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_order.OrderModel'),
        ),
    ]
