# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sx_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='goods',
            field=models.CharField(max_length=150),
        ),
    ]
