# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sx_order', '0002_auto_20190221_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='goods',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='good_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
